### PR TITLE
Update RelationshipStyle.php

### LINKED ISSUE #47: Relationship attribute "dashed" not supported
If `dashed` is false, it is not exported

### PR DESCRIPTION
**Pull request by smalot**
fix #47

### CODE REVIEW

**Comment by norberttech** [comment]
hey I fixed issues with failing tests and moved from `master` to `1.x` - could you please rebase this pull request?

**Comment by smalot** [comment]
the pull request has been rebased but I don't understand why there is an issue during static analysis

**Comment by norberttech** [comment]
php cs fixer is failing, please run composer cs:php:fix locally and commit changes

**Comment by smalot** [comment]
Fixed !

**Pull request merged**
